### ISSUE TITLE
GitHub Data Analysis

### ISSUE THREAD

**Issue by CSchank** [smiths/spreadOverTimeAndTeam#1]
Issue for discussion and progress on GitHub data analysis. 

Some preliminary data:

2022/23 Daily Commits:
<img width="1709" alt="image" src="https://github.com/user-attachments/assets/d02b3f2c-1697-4656-8887-a87b71863e02">

2023/24 Daily Commits:
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/f3185d2a-a06e-4969-8768-a6486ed8b0fa">

Some interesting notes:
- We definitely see the "due date effect" pretty strongly. It might be interesting to also add up all the commits in say, the previous three days, or do a three-day rolling average.
- 2022-23 seems to have a stronger version of this effect. Can you think of things we've done that might have helped last year? We did have a smaller class (and sample size - only 11 of the repos were still accessible).

Next I'm going to work on the teammate data.

**Comment by smiths** [comment]
We started using the team self-reported metrics last year after the POC demo in November.  Maybe that had an effect.  That would be nice because in the current paper we are hoping to argue that using team self-reporting from the start will help with accountability.  We also require teams to create issues related to meeting and to keep agendas.  I started that last year, but I've emphasized it more this year.

**Comment by CSchank** [comment]
Okay! Sounds good. Interesting to see there is already an apparent effect.

Authors are very much more annoying. The data is very messy because of them having different GitHub accounts. I'm working on it, but it has taken much more time!!!

**Comment by smiths** [comment]
This is frustrating!  Don't feel like you have to do all of them.  A representative sample should be fine.  I hope it helps clean up the data going forward that we ask for each team members GitHub username.  Some will probably still use more than one name, but we can remind them that we expect the data to be under one name per team member.

**Comment by CSchank** [comment]
Yes, GitHub/GitLab is annoying in that it just "trusts" the name that Git tells it. So you can end up with several names for the same people, even if they're the same GitHub account. I've done it before too, it's annoying! The big problem is if they've set up their local Git to use GitLab, which might be configured to use their MacID instead. Anyways, I have a script that uses fuzzy matching and then asks you "Is [a] actually [b]?" to confirm. Works for the most part unless the names are really weird!

**Comment by CSchank** [comment]
@smiths here are 9 teams from last year (had to throw some out due to unrecoverable mappings between teammates). The first graph is the ratio between the person with the most and the least commits on the on the team. E.g. 8 means that the top committer had 8 times as many commits as the bottom committer.

<img width="611" alt="image" src="https://github.com/user-attachments/assets/2300733f-490d-4d61-b2cf-63b2c0ad7c0d">

For the second graph I wanted to calculate something that would give us a better idea how fair the teams are. Max/min is a good start, but doesn't really tell you the whole story. I tried many things like standard deviations, and I tried Googling around to see if something like this already existed, but I couldn't find anything. I wanted something that would capture how "fair" the distribution of commits (could also be LOC, etc later) is. In particular:

- It should be a value from 0 to 1; normalized by the number of commits and number of teammates
- If one person does all the work, fairness should be 0.
- If everyone does equal work, fairness should be 1.
- Adding more teammates who contribute unfairly should make it go down, all else being equal. E.g. if I do 50% of the
commits in a team of 3, that's more fair than if I did 50% of the commits in a team of 4.

What I came up with is what I'm calling an "unfairness score" for the team. This is calculated as the average number of "extra" commits you've done compared to any of your teammates, which I call "unfair commits". For instance, if I have 10 commits and my three teammates each have 5, then on average, I did 5 more commits than my teammates, on average. So the total number of unfair commits is 5, and the unfairness score is 5/25=0.2, for a fairness score of 0.8. Here are some
other examples:

```
fairness([10,10,0]) = 0.5
fairness([10,10,0,0]) = 0.3333...
fairness([10,0,0]) = 0
fairness([10,10,10]) = 1
fairness([11,11,0]) = 0.5
```

I still want to play with this more to see how it behaves in various situations, but it seems to work pretty well. No idea if I've discovered something new, I kind of doubt it! Either way, might be a neat way to measure teammates fairness.

But here is a graph from our data:

<img width="629" alt="image" src="https://github.com/user-attachments/assets/1ec445a5-33a4-4e76-bd28-8afc3b4349d3">


We can also make these "unfairness plots" which compare teammates' relative unfairness to each other.

<img width="570" alt="image" src="https://github.com/user-attachments/assets/c519f4a5-8b70-498b-867d-a49885bc8e16">

**Comment by smiths** [comment]
Very cool @CSchank!  Your plots and thought process are great.  We won't have any problem filling 5 pages.  We actually are going to have trouble getting everything into the 5 pages.  

The heat map is the only one that confuses me.  I don't know how to read it.  :smile:

Having a fairness metric is a neat idea.  I like your thought process.  I think you are on to something.  Your rationale sounds good, but I'm not completely sure. 

I did some googling and found [Jain's fairness index](https://reimbar.org/posts/jain-fairness/).  This index is used to measure the fairness of allocating a resource, like the size of a piece of pie to each person involved, or the bandwidth available to a network connection.  At first it seems different, since getting the resource is a "good" thing to the recipient, but getting more commits is a "bad" thing.  I thought about it further though and the notion of fairness seems to track to commits.  Someone getting more commits is unfair.  Dividing up all the commits equally is fair.

Jain's metric behaves the same for completely fair.  If everyone gets the same number of commits the index is 1.  It is different for when one agent gets all the commits.  In this case the index is 1/n, where n is the number of agents.  The number gets closer to zero the more agents are involved.  I actually like this.  Your metric will be zero no matter how many people commit, but following your argument that adding teammates causes the metric to go down, it does become more unfair the more people there are if one person is doing all the work.

Jain's metric also satisfies your "adding more teammates who contribute unfairly should make it go down."  The numbers are not the same as your metric.

If it isn't too much work, could you make your plot using Jain's fairness index?

**Comment by CSchank** [comment]
The heat maps are comparing teammates and light up more strongly with red the more commits someone does than the other person. For the plot I took the absolute value, hence the symmetry. Like 

Wow, clearly my search wasn't long enough! Looking at Jain's, it is doing something where it squares the values, which mine doesn't do. One of the ones I tried did give me 1/n when someone does all the commits, but I tweaked it because I liked the idea of that being 0 😅 I was looking at it like, I consider having done all the work completely and utterly 0% fair! There were some nice properties of that 1/n one I tried though. I will look at Jain's index and compare the values tomorrow. It certainly seems easier to compute, though I may be able to optimize mine.

**Comment by smiths** [comment]
Thank you for the explanation of the heat maps @CSchank.  We should probably look at Jain's justification for his index before we get too serious about it.  We are also probably okay to fake it somewhat.  This is an ideas paper after all.  I certainly am liking the ideas that are coming up so far.  :smile:

**Comment by christopheranand** [comment]
The daily commits are not as bad as they could be.  They do keep working on the project throughout the year, outside the exam/holiday time.  

For the fairness, I know some people make very large commits because they don't think about breaking their work up into pieces so their code doesn't compile for a long time.  How hard would it be to also measure lines of code?  Maybe just mention that as something to look at in the full paper.  If you use Jain's fairness, which seems related to the standard deviation, then you don't even need to include a formula or any explanation in the paper.  So it saves on space and things you need to explain. 

I also didn't understand the heat map, so given the page constraint, it is safe to drop it.

**Comment by CSchank** [comment]
Here is the Jain's fairness metric for the same teams.

<img width="630" alt="image" src="https://github.com/user-attachments/assets/a6e07365-5420-4097-a108-db480161f5c6">

Here's a comparison of the two metrics. They are generally the same (ranking is identical I think), but Jain tends to be more favourable, probably because it has the squares in it. Ours has the advantage that the number actually represents the proportion of commits which are unfair. If I understand correctly, Jain's is a bit harder to understand what the number means (at least, in between the extreme cases).

<img width="603" alt="image" src="https://github.com/user-attachments/assets/932a10d9-a0b5-4b5b-ac03-7f2b4b7d9e01">

Lines of code we can look at, but sometimes thats very inaccurate being someone commits an entire library by accident then removes it (or doesn't). 

The heatmap is a comparison of teammates to other teammates, looking at the relative "unfairness" amongst them. But yes, for now we don't have to include it.

**Comment by CSchank** [comment]
I agree about the daily commits - it already seems like our strategies have started working. We did have a smaller class last year, which may affect things a bit, but probably this metric isn't as affected. If anything you might expect the smaller class to be less evenly distributed all else being equal. We'll see what happens this year with a larger class.

**Comment by CSchank** [comment]
Also: here are some more calculations and stats. I calculated how many commits were made in the 2, 1 and 0 days before the due dates in red (I'll call due dates T-0 days and the three days [T-2..T-0]). This ignores the presentation ranges in orange. Here's what I found:

|    Stat     |  2022/23      |  2023/24  |
| ------------- | ------------- | ------------- |
| Total Days | 243 | 244 |
| Total Commits  |  10435 | 3936 |
| [T-2..T-0] Days  |  30  | 30 |
| Percentage of [T-2..T-0] Days  |  12.35% | 12.30% |
| Commits in [T-2..T-0]  |  5220  | 1443 |
| Commits in [T-2..T-0] (%)  |  50.02%  | 36.66% |
| T-0 Days | 10  | 10  |
| T-0 Days (%)  |  4.12%  |  4.09% |
| Commits on T-0  |  3492  |  711 |
| Commits on T-0 (%)  |  33.46%  | 18.06%  |

For example, even in 2023/24, which was the better year, 36.66% of the commits still happened in only 12.30% of the days. 2022/23 was especially bad, with 50% of commits happening within 3 days of due dates, and 33% on the due dates themselves! This shows that things are still concentrated around the due dates quite a bit. Obviously, this is always going to happen, but it would be good to try to improve things, and I think this data would be a good way to illustrate the problem in the idea paper. Plus, we have the advantage of showing that improvements we made previously did help to alleviate this already. And hopefully we can do even better this year! 

It should be noted that this does not take weekends or holidays into account (another threat to validity!)

**Comment by smiths** [comment]
Great work @CSchank!  This is plenty of content for the paper.  If we can get the paper accepted, then we might be able to get some good feedback on the best measures of fairness.  

I have some other deadlines, but I hope to get back to serious effort on this paper soon.

**Comment by smiths** [comment]
This task has been completed, so this issue can be closed.
