### ISSUE TITLE
Produce new plots for fairness metric 

### ISSUE THREAD

**Issue by CSchank** [smiths/spreadOverTimeAndTeam#7]
- [x] Include only SE students in the first year
- [x] Sort teams in ascending order
- [x] Compute average fairness for teams each year

**Comment by CSchank** [comment]
@smiths what do you think of these plots? They use TikZ.

Unfortunately, the average fairness metric went down last year. This of course could be explained by lots of things: I don't think this includes commits in branches that have been deleted and not merged, could be there was more pair programming, and of course all the "usual" things like how commits may not be reflective of work done, etc. I think it's worth leaving in the paper as a future work to try to improve, and exploring whether or not this number can be correlated with the perceived fairness of the teams. It would also be interesting to know if this is correlated with teams' grades in the course.

I was able to recover the data of two more teams in 2023/24 using the GitHub contributions API that goes by GitHub account instead of Git committer name.

Currently I just put them in another paper I'm working on on Overleaf, to reduce the chance of merge conflicts until I'm ready to put them in. :)

<img width="341" alt="image" src="https://github.com/user-attachments/assets/8df7cf36-fc93-402a-9001-c24d90983681">

**Comment by smiths** [comment]
Those plots are great!  Exactly what I was hoping for in terms of the look of the graphs.  The results could have been more positive for our narrative, but it isn't a big deal.  The numbers weren't a lot worse, and we didn't have the team charter in place last year.  We can show an idea of how we plan to measure fairness.  If we are lucky the paper will be accepted and we'll get great feedback.

Can you produce pdfs of the plots without the captions?  We can put the plots in the paper.  (We might just put one plot in the paper, since they don't really look that different.  It depends how much space we have.)

**Comment by CSchank** [comment]
I can do much better than PDFs! I have LaTeX code! I'll make a branch.
